import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import CartProvider from './components/Provider';
import ShoppingCartModal from './components/ShoppingCartModal';
import ClientSessionProvider from './components/ClientSessionProvider';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Qadir Store',
  description: 'Qadir Store is your one-stop destination for trendy and stylish products for men, women, and teens. Our carefully curated collection features the latest in fashion, ensuring you stay ahead of the trends. Whether you\'re looking for chic outfits for women, dapper attire for men, or cool and casual styles for teens, Qadir Store has something for everyone. Discover a wide range of clothing, accessories, and more, all designed to cater to your fashion needs. Step into Qadir Store and elevate your style game today!',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientSessionProvider>
          <CartProvider>
            <Navbar />
            <ShoppingCartModal />
            <Toaster /> {/* Add Toaster component here */}
            {children}
          </CartProvider>
        </ClientSessionProvider>
      </body>
    </html>
  );
}


// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/Navbar";
// import CartProvider from "./components/Provider";
// import ShoppingCartModal from "./components/ShoppingCartModal";
// import ClientSessionProvider from "./components/ClientSessionProvider";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Qadir Store",
//   description:
//     "Qadir Store is your one-stop destination for trendy and stylish products for men, women, and teens. Our carefully curated collection features the latest in fashion, ensuring you stay ahead of the trends. Whether you're looking for chic outfits for women, dapper attire for men, or cool and casual styles for teens, Qadir Store has something for everyone. Discover a wide range of clothing, accessories, and more, all designed to cater to your fashion needs. Step into Qadir Store and elevate your style game today!",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <ClientSessionProvider>
//           <CartProvider>
//             <Navbar />
//             <ShoppingCartModal />
//             {children}
//           </CartProvider>
//         </ClientSessionProvider>
//       </body>
//     </html>
//   );
// }

// import type { Metadata } from "next";
// import { Inter, Noto_Sans_Bassa_Vah } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/Navbar";
// import CartProvider from "./components/Provider";
// import ShoppingCartModal from "./components/ShoppingCartModal";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//       <CartProvider>
//       <Navbar />
//       <ShoppingCartModal/>
//       {children}
//       </CartProvider>
//         </body>
//     </html>
//   );
// }
