import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import CartProvider from "./components/Provider";
import ShoppingCartModal from "./components/ShoppingCartModal";
import ClientSessionProvider from "./components/ClientSessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientSessionProvider>
          <CartProvider>
            <Navbar />
            <ShoppingCartModal />
            {children}
          </CartProvider>
        </ClientSessionProvider>
      </body>
    </html>
  );
}





// import type { Metadata } from "next";
// import { Inter, Noto_Sans_Bassa_Vah } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/Navbar";
// import CartProvider from "./components/Provider";
// import ShoppingCartModal from "./components/ShoppingCartModal";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//       <CartProvider>
//       <Navbar />
//       <ShoppingCartModal/>
//       {children}
//       </CartProvider>
//         </body>
//     </html>
//   );
// }
